{"timestamp":"2025-07-17T19:15:02.273008","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-17T19:15:02.275532","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-17T19:15:10.338895","level":"info","event":"Starting weather data fetch from Open-Meteo API","logger":"unusual_prefix_39d5b4c4fb0e26bd2861cde9a37101b8f5d54193_dag"}
{"timestamp":"2025-07-17T19:15:17.969590","level":"info","event":"Coordinates 52.5483283996582°N 13.407821655273438°E","logger":"unusual_prefix_39d5b4c4fb0e26bd2861cde9a37101b8f5d54193_dag"}
{"timestamp":"2025-07-17T19:15:17.971183","level":"error","event":"Error fetching weather data: object of type 'int' has no len()","logger":"unusual_prefix_39d5b4c4fb0e26bd2861cde9a37101b8f5d54193_dag"}
{"timestamp":"2025-07-17T19:15:17.971965","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"TypeError","exc_value":"object of type 'int' has no len()","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.10/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":867,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.10/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1159,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.10/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.10/site-packages/airflow/sdk/bases/decorator.py","lineno":251,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.10/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.10/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/dag.py","lineno":63,"name":"fetch_weather_data"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-17T23:18:55.472527","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-17T23:18:55.478795","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-17T23:19:27.683740","level":"error","event":"Process timed out, PID: 158","logger":"airflow.utils.timeout.TimeoutPosix"}
{"timestamp":"2025-07-17T23:19:28.254271","level":"error","event":"Failed to import: /opt/airflow/dags/dag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"AirflowTaskTimeout","exc_value":"DagBag import timeout for /opt/airflow/dags/dag.py after 30.0s.\nPlease take a look at these docs to improve your DAG import time:\n* https://airflow.apache.org/docs/apache-airflow/3.0.2/best-practices.html#top-level-python-code\n* https://airflow.apache.org/docs/apache-airflow/3.0.2/best-practices.html#reducing-dag-complexity, PID: 158","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":883,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":241,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/dag.py","lineno":3,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.10/site-packages/pandas/__init__.py","lineno":46,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.10/site-packages/pandas/core/api.py","lineno":47,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.10/site-packages/pandas/core/groupby/__init__.py","lineno":1,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.10/site-packages/pandas/core/groupby/generic.py","lineno":67,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/timeout.py","lineno":69,"name":"handle_timeout"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-17T23:19:28.353350","level":"error","event":"DAG not found during start up","dag_id":"weather_data_collection_dag","bundle":"BundleInfo(name='dags-folder', version=None)","path":"dag.py","logger":"task"}
{"timestamp":"2025-07-17T23:19:38.469844Z","level":"warning","event":"Process exited abnormally","exit_code":1,"logger":"task"}
